name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'


jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    #container: shiftleft/core:latest
    
    steps:
      - uses: actions/checkout@v4
        
      # - name: preZero Static Analysis
      #   run: |
      #     curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
      #     ${GITHUB_WORKSPACE}/sl analyze --verbose --wait --app jssrc2cpgtest .
      #   env:
      #     SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          
      - name: preZero Static Analysis
        run: |
          # Invoke-WebRequest -Uri https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip -UseBasicParsing -OutFile sl-latest-windows-x64.zip
          # Expand-Archive -Path sl-latest-windows-x64.zip -DestinationPath .
          echo ${GITHUB_REPOSITORY#*/}
          echo "============="
          echo ${{ github.event.repository.name }}
          #.\sl.exe analyze --verbose --app testingexcludeonwindows . -- --exclude "BZ1152513,keys"
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
