name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  push:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - name: Qwiet-AllInOne-Scan
    #   uses: elangosenthilnathan/Qwiet-preZero@v0.0.1
    #   with:
    #     shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    #     verbose: false
    #     strict: true
    #     wait: false
    #     importGitHub: false

    - name: Check OS and Install Relevant Qwiet Client
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          curl https://cdn.shiftleft.io/download/sl > $HOME/sl && chmod a+rx $HOME/sl
          sudo mv $HOME/sl /usr/local/bin/
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -UseBasicParsing -OutFile sl-latest-windows-x64.zip
          Expand-Archive -Path sl-latest-windows-x64.zip -DestinationPath .
          $env:Path = $env:Path + ";.\sl" +  ";." 
        else
          echo "Unsupported OS: ${{ runner.os }}"
          exit 1
        fi 

    - name: Publish PR Comment
      #if: github.event_name == 'pull_request'
      run: |
          sl check-analysis --v2 --app "${GITHUB_REPOSITORY_OWNER}-${GITHUB_REPOSITORY#*/}" --no-build-rules --report-file checkanalysis-report.md
          COMMENT_ID=2758540197
          PR_NUMBER=16

          url="https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY#*/}/issues/${PR_NUMBER}/comments"
          curl -X GET \
            -H "Authorization: token ${GH_API_TOKEN}" \
            -H "Accept: application/vnd.github.raw+json" \
            ${url} -o response.json

          updateCommentID=0
          jq -r '.[] | @base64' response.json | while read -r row; do
            # Decode the base64 string back to JSON
            decoded_row=$(echo "${row}" | base64 --decode)
          
            # Extract values using jq
            commentID=$(echo "${decoded_row}" | jq -r '.id')
            body=$(echo "${decoded_row}" | jq -r '.body')
          
            if echo ${body} | grep -q "Checking analysis of application"; then
                updateCommentID=$commentID
                echo "Comment ID is $commentID"
                exit
            fi
          done
          
          #echo "issue_title=$(jq -r '.[0].title' data.json)" >> $GITHUB_OUTPUT
          echo "Comment ID is $updateCommentID"

          url="https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY#*/}/issues/comments/${updateCommentID}"
          curl -X PATCH \
            -H "Authorization: token ${GH_API_TOKEN}" \
            -H "Accept: application/vnd.github.raw+json" \
            -d "$(jq -Rs '{"body": .}' checkanalysis-report.md)" \
            ${url}
            
          # url="https://api.github.com/repos/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY#*/}/issues/16/comments"
          # curl -X POST \
          #   -H "Authorization: token ${GH_API_TOKEN}" \
          #   -H "Accept: application/vnd.github.raw+json" \
          #   -d "$(jq -Rs '{"body": .}' checkanalysis-report.md)" \
          #   ${url}
          #python3 ghComment.py --github_org "${GITHUB_REPOSITORY_OWNER}" --github_repo "${GITHUB_REPOSITORY#*/}" --github_pat ${GH_API_TOKEN} --github_pr_number 16 --filename  checkanalysis-report.md
      
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GH_API_TOKEN: ${{ secrets.GHPAT }}          
          

