name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'


jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    container: shiftleft/core:latest
    
    steps:
      - uses: actions/checkout@v4
        
  
      - name: preZero Static Analysis
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
          ${GITHUB_WORKSPACE}/sl analyze --verbose --wait --app jssrc2cpgtest .
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
